@startuml
actor Author
actor Editor
actor Reviewer
actor ProofReader

rectangle "Journal" {
    Author - (SendPaper)
    Editor - (Review)
    Reviewer - (Review)
    Editor - (SendPaper)
    ProofReader - (PrepareForPublishing)

    (SendPaper) --> (Review) : <<include>>
    (PrepareForPublishing) --> (SendPaper) : <<extend>> 
}

@enduml
