@startuml
actor OCRModule

rectangle "MorphologyModule" {
 

    OCRModule - (CheckWordLanguage)
    OCRModule - (GetBaseForm)
    OCRModule - (GetGrammarMeaning)
    OCRModule - (GetSimilarWords)

    (CheckWordLanguage) -down-> (GetBaseForm): <<include>>
    (GetBaseForm) -down-> (GetGrammarMeaning): <<include>>
    (GetBaseForm) -down-> (GetSimilarWords): <<include>>
}



@enduml
