@startuml
actor OCRModule

rectangle "MorphologyModule" {
 

    OCRModule - (CheckWordLanguage)
    OCRModule - (GetBaseForm)
    OCRModule - (GetGrammarMeaning)

    (CheckWordLanguage) <-down- (GetBaseForm): <<extend>>
    (GetBaseForm) <-down- (GetGrammarMeaning): <<extend>>
    (GetBaseForm) <-down- (GetSimilarWords): <<extend>>
}



@enduml
