@startuml
actor ResponsiblePerson as RP
actor Operator
actor Controller

rectangle "Doc System" {
    RP - (AttachIssue)
    RP - (AttachResolution)
    RP - (AttachDocument)
    Operator - (DeleteDocument)
    Controller - (DeleteDocument)
    (AttachIssue) -down-> (AttachDocument): <<include>>
    (AttachResolution) -down-> (AttachDocument): <<include>>
    (AttachDocument) --> (SendAnnouncement): <<extend>>
}

@enduml
