@startuml
actor User
actor SuperUser
actor PluginsServer

User -> (ConfigurePlugins)
User -> (SelectPlugin)
User -> (ChangeSettings)
User -> (UpdatePlugins)

SuperUser -> (UpdatePluginsList)
SuperUser -> (DeletePlugins)
SuperUser -> (InstallPlugins)
SuperUser -> (CheckPluginsList)

(ConfigurePlugins) -down-> (SelectPlugin) : Выбор плагина
(SelectPlugin) -down-> (ChangeSettings) : Настройка плагина
(UpdatePlugins) -right-> PluginsServer : Обновление с сервера
(UpdatePluginsList) -down-> PluginsServer : Обновление списка плагинов
(DeletePlugins) -down-> PluginsServer : Удаление плагинов
(InstallPlugins) -down-> PluginsServer : Установка плагинов
(CheckPluginsList) -down-> PluginsServer : Просмотр списка плагинов

@enduml
