@startuml
actor Linguist
actor Programmer
actor BuildServer
actor Semantics

rectangle "MorphoDB" {
    Linguist - (ModifyData)
    Linguist - (Compile)
    Linguist - (ExportData)

    Programmer - (ModifyData)
    Programmer - (Compile)
    Programmer - (ExportData)
    Programmer - (ExportDataForDebug)

    BuildServer - (Compile)

    Semantics - (ExportWordList)

    (ModifyData) -down-> (AddWord): <<include>>
    (ModifyData) -down-> (RemoveWord): <<include>>
    (ModifyData) -down-> (ChangeWord): <<include>>
    (ModifyData) -down-> (CheckDataIntegrity): <<extend>>
    (CheckDataIntegrity) -down-> (RemoveWord): <<extend>>

    (ExportData) -down-> (ExportWordList): <<include>>

}

@enduml
