@startuml
actor Linguist
actor Programmer
' actor BuildServer
' actor Semantics

rectangle "MorphoDB" {
    Linguist - (ModifyData)
    Linguist - (ExportData)

    Programmer - (ModifyData)
    Programmer - (ExportData)

    ' BuildServer - (Compile)

    ' Semantics - (ExportWordList)

    (ExportData)-down-> (Debug): <<extend>>
    (ExportData)-down-> (Compile): <<include>>
    (ModifyData) -down-> (AddWord): <<include>>
    (ModifyData) -down-> (RemoveWord): <<include>>
    (ModifyData) -down-> (Compile): <<include>>
    (ModifyData) -down-> (ChangeWord): <<include>>
    (ModifyData) -down-> (CheckDataIntegrity): <<extend>>
    (CheckDataIntegrity) -down-> (RemoveWord): <<extend>>

    (ExportData) -down-> (ExportWordList): <<include>>

}

@enduml
