@startuml
actor Person
entity Lift

' Пассажир нажимает кнопку для закрытия дверей
Person -> Lift : pressDoors

' Пассажир выбирает этаж
Person -> Lift : pressButton(floor)

alt лифт не двигается
  Person -> Lift : pressDoors
end

' Лифт закрывает двери и начинает движение
Lift -> Lift : startMoving
note right of Lift : лифт движется 3 секунды на этаж

' Лифт сообщает о проезжаемых этажах
Lift -> Person : floorReached (floor1)
Lift -> Person : floorReached (floor2)
Lift -> Person : floorReached (floor3)
Lift -> Person : floorReached (floor4)
Lift -> Person : floorReached (floor5)

' Лифт останавливается
Lift -> Lift : stopMoving

alt лифт не двигается
  Person -> Lift : pressDoors
end
@enduml
