@startuml
actor User
participant Cabin
entity FloorButton
entity Algorithm

' Кооперация с линией жизни для алгоритма
entity SelectFloor

alt Цикл проверки всех кнопок этажей
  loop для каждого этажа
    FloorButton -> Cabin : isPressed
    alt кнопка нажата
      Cabin -> Algorithm : selectFloor(floor)
    end
  end
end

' Кооперация взаимодействует с алгоритмом
SelectFloor -> Algorithm : selectFloor(floor)
@enduml
