@startuml
' Диаграмма компонентов с указанием размещения:

interface IMorphologyData
interface IDataExport
interface IErrorHandler
interface IMorphology

node MorphoDB {
    component Database {
        [Database] .. IMorphologyData
        [Database] .. IDataExport
    }
}

node LinguistPlace {
    component DataClient {
        [DataClient] .. IMorphologyData
    }
    component Export {
        [Export] .. IDataExport
    }
    component Compiler {
        component Parser
        component Handler {
            [Handler] .. IErrorHandler
        }
        component Builder {
            [Builder] .. IMorphology
        }
    }
}

Parser --> Handler
Builder --> Handler
Builder .. IMorphology
@enduml
