@startuml 2
[*] --> Draft

Draft :
Draft --> OnReview : sent

OnReview : 
OnReview : do/ Рецензирование
OnReview --> Accepted : approved
OnReview --> Draft : declined

Accepted : 

OnReview --> Checked : checking

Checked : 
Checked --> OnCorrection : correct
Checked --> OnReview : review completed

OnCorrection :
OnCorrection --> Checked : sent
OnCorrection --> Draft : if not sent in 10 days

@enduml
